### ISSUE TITLE
not working (Windows server wampserver

### ISSUE THREAD

**Issue by FevLoad** [nitmir/XDCCParser-global#2]
the script is not working
can not load bot list
error can not load bot list from http: 0.0.0.0:7000

**Comment by nitmir** [comment]
From the very few information you provided, this program is working and your using it bad as  0.0.0.0 is not a valid IP address, thus it cannot load anything from it as stated by the error message.
If you can figure out any bug and patch it, I welcome any pull requests. Otherwise, I do not offer any kind of support for this project as it is manly just an archive of an offline repository.

I hope you can resolve your problem
